CC    = gcc
CFLAGS = -g

all: stack-overflow1 stack-overflow2

stack-overflow1: stack-overflow1.c
	$(CC) $(CFLAGS) stack-overflow1.c -o stack-overflow1

stack-overflow2: stack-overflow2.c
	$(CC) $(CFLAGS) stack-overflow2.c -o stack-overflow2

clean:
	rm stack-overflow1 stack-overflow2

