#!/bin/sh
# <oldrev> <newrev> <refname>
# docs:
# https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
# https://docs.gitlab.com/ee/administration/server_hooks.html
# https://git-scm.com/docs/githooks#pre-receive

echo "PATH: ${PATH}"

while read -r oldrev newrev _ ; do
    # old revision is blank - branch creation
    if [ "$oldrev" = "0000000000000000000000000000000000000000" ] ||
         # new revision is blank - branch deletion
         [ "$newrev" = "0000000000000000000000000000000000000000" ] ;
    then
        # create new or delete old branch
        continue;
    fi
    echo "git diff --no-color -U0 $oldrev $newrev"
    git diff --no-color -U0 "$oldrev $newrev" 2>&1
done
exit 1;
